language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  matrix:
    - LARAVEL=5.6.*
    - LARAVEL=5.7.*
    - LARAVEL=5.8.*
    - LARAVEL=^6.0
    - LARAVEL=^7.0
    - LARAVEL=^8.0

matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: LARAVEL=^6.0
    - php: 7.1
      env: LARAVEL=^7.0
    - php: 7.1
      env: LARAVEL=^8.0
    - php: 7.2
      env: LARAVEL=^8.0

install:
  - travis_retry composer require "illuminate/contracts=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit
